### DELETE a Item to the Catalog collection

curl --request DELETE \
    --url https://localhost:5188/catalog/3 \
    --header 'authorization: Bearer {eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjctTUVKT2tKMUVURTItcmlkeWJyNiJ9.eyJpc3MiOiJodHRwczovL2Rldi04ajJwbTBsNW1wcDVwNHd3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ1cUV6WVFYb2RyOWVYaDQ5QWNOV1FHWExXdXU2QVVCc0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9nb2xkZW4tZWFnbGUiLCJpYXQiOjE3MDEzNzk1NjIsImV4cCI6MTcwMTQ2NTk2MiwiYXpwIjoidXFFellRWG9kcjllWGg0OUFjTldRR1hMV3V1NkFVQnMiLCJzY29wZSI6ImRlbGV0ZTpjYXRhbG9nIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.XDmJLraQTQZEXLEkDbi-KO2rWo-VjwVH-EsOfKdlebKMfECmdrcu8LDIiLOni2wFfD5qrBRQX_sHzs8meB8iTBJGlPcMsM3_iSblkX-78DPHGRYcBWCdc4lw0pTcL5omH6VM-KFBS9wx64Xb60FYcNmcv10yH8AV_vVWem5mcqIf6qJ8nIoJ-JPTuYtNDepAzOvOA0q-mIO07abmjUS-Z4ruG9K4aindSQxJNI4t-ItZAW43Zwv8s4H_nPVt-wVcLvKAiLd9nRTYqktLEjnUV71VpvUV9hd-WFqO9OfNEYp6A2Wb15pj5CsHLBYajZmvpyv0tI24gHgPyKzOc-NVSA}'